// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_PUZZLEPIECES = 'SET_PUZZLEPIECES';
export const SET_PUZZLEPIECE = 'SET_PUZZLEPIECE';
export const LIKE_PUZZLEPIECE = 'LIKE_PUZZLEPIECE';
export const UNLIKE_PUZZLEPIECE = 'UNLIKE_PUZZLEPIECE';
export const DELETE_PUZZLEPIECE = 'DELETE_PUZZLEPIECE';
export const POST_PUZZLEPIECE = 'POST_PUZZLEPIECE';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';